let bananaList = [/* 轮播图 */
  {id:'001',src:'/image/index_img/banana/banana_01.jpg'},
  {id:'002',src:'/image/index_img/banana/banana_02.jpg'},
  {id:'003',src:'/image/index_img/banana/banana_03.jpg'},
  {id:'004',src:'/image/index_img/banana/banana_04.jpg'}
]
let activityList = [/* 福利中心 */
  {id:'001',headLine:'#喝咖啡挑战',title:'再喝一单达成挑战'},
  {id:'002',headLine:'本月咖啡达人',title:'马上冲榜'},
  {id:'003',headLine:'lucky送福利',title:'领4.8折券'},
  {id:'004',headLine:'邀请好友',title:'每邀1位好友各得20元'}
]
let commodityList = [/* 商品数据 */
  {
    title:'阿馥奇朵',
    price:'89',
    originalPrice:'129',
    sale:'41900',
    gabalnara:true,
    url:'/image/index_img/merchandise/coffee001.jpg',
    information:[
      {
        title:'杯型',
        select:[
          {
            size:'大杯',
            price:'5'
          },
          {
            size:'中杯',
            price:'3'
          },
          {
            size:'小杯',
            price:'0'
          }
        ]
      },
      {
        title:'温度',
        select:[
          {
            size:'热',
            price:'0'
          },
          {
            size:'冷',
            price:'0'
          }
        ]
      },
      {
        title:'糖度',
        select:[
          {
            size:'不另外加糖',
            price:'0'
          },
          {
            size:'半糖',
            price:'0'
          },
          {
            size:'标准糖',
            price:'0'
          }
        ]
      },
    ]
  },
  {
    title:'麦芽雪冷萃',
    price:'69',
    originalPrice:'139',
    sale:'5900',
    gabalnara:true,
    url:'/image/index_img/merchandise/coffee002.jpg',
    information:[
      {
        title:'杯型',
        select:[
          {
            size:'大杯',
            price:'5'
          },
          {
            size:'中杯',
            price:'3'
          },
          {
            size:'小杯',
            price:'0'
          }
        ]
      },
      {
        title:'温度',
        select:[
          {
            size:'热',
            price:'0'
          },
          {
            size:'冷',
            price:'0'
          }
        ]
      },
      {
        title:'糖度',
        select:[
          {
            size:'不另外加糖',
            price:'0'
          },
          {
            size:'半糖',
            price:'0'
          },
          {
            size:'标准糖',
            price:'0'
          }
        ]
      },
    ]
  },
  {
    title:'冷萃浮乐朵',
    price:'45',
    originalPrice:'79',
    sale:'6900',
    gabalnara:false,
    url:'/image/index_img/merchandise/coffee003.jpg',
    information:[
      {
        title:'杯型',
        select:[
          {
            size:'大杯',
            price:'5'
          },
          {
            size:'中杯',
            price:'3'
          },
          {
            size:'小杯',
            price:'0'
          }
        ]
      },
      {
        title:'温度',
        select:[
          {
            size:'热',
            price:'0'
          },
          {
            size:'冷',
            price:'0'
          }
        ]
      },
      {
        title:'糖度',
        select:[
          {
            size:'不另外加糖',
            price:'0'
          },
          {
            size:'半糖',
            price:'0'
          },
          {
            size:'标准糖',
            price:'0'
          }
        ]
      },
    ]
  },
  {
    title:'气致冷萃浮乐朵',
    price:'129',
    originalPrice:'229',
    sale:'9100',
    gabalnara:true,
    url:'/image/index_img/merchandise/coffee004.jpg',
    information:[
      {
        title:'杯型',
        select:[
          {
            size:'大杯',
            price:'5'
          },
          {
            size:'中杯',
            price:'3'
          },
          {
            size:'小杯',
            price:'0'
          }
        ]
      },
      {
        title:'温度',
        select:[
          {
            size:'热',
            price:'0'
          },
          {
            size:'冷',
            price:'0'
          }
        ]
      },
      {
        title:'糖度',
        select:[
          {
            size:'不另外加糖',
            price:'0'
          },
          {
            size:'半糖',
            price:'0'
          },
          {
            size:'标准糖',
            price:'0'
          }
        ]
      },
    ]
  },
  {
    title:'冷萃冰咖啡',
    price:'73',
    originalPrice:'119',
    sale:'41200',
    gabalnara:true,
    url:'/image/index_img/merchandise/coffee005.jpg',
    information:[
      {
        title:'杯型',
        select:[
          {
            size:'大杯',
            price:'5'
          },
          {
            size:'中杯',
            price:'3'
          },
          {
            size:'小杯',
            price:'0'
          }
        ]
      },
      {
        title:'温度',
        select:[
          {
            size:'热',
            price:'0'
          },
          {
            size:'冷',
            price:'0'
          }
        ]
      },
      {
        title:'糖度',
        select:[
          {
            size:'不另外加糖',
            price:'0'
          },
          {
            size:'半糖',
            price:'0'
          },
          {
            size:'标准糖',
            price:'0'
          }
        ]
      },
    ]
  },
  {
    title:'轻甜奶油冷萃',
    price:'89',
    originalPrice:'119',
    sale:'9100',
    gabalnara:false,
    url:'/image/index_img/merchandise/coffee006.jpg',
    information:[
      {
        title:'杯型',
        select:[
          {
            size:'大杯',
            price:'5'
          },
          {
            size:'中杯',
            price:'3'
          },
          {
            size:'小杯',
            price:'0'
          }
        ]
      },
      {
        title:'温度',
        select:[
          {
            size:'热',
            price:'0'
          },
          {
            size:'冷',
            price:'0'
          }
        ]
      },
      {
        title:'糖度',
        select:[
          {
            size:'不另外加糖',
            price:'0'
          },
          {
            size:'半糖',
            price:'0'
          },
          {
            size:'标准糖',
            price:'0'
          }
        ]
      },
    ]
  },
  {
    title:'绵云冷萃',
    price:'269',
    originalPrice:'518',
    sale:'400',
    gabalnara:false,
    url:'/image/index_img/merchandise/coffee006.jpg',
    information:[
      {
        title:'杯型',
        select:[
          {
            size:'大杯',
            price:'5'
          },
          {
            size:'中杯',
            price:'3'
          },
          {
            size:'小杯',
            price:'0'
          }
        ]
      },
      {
        title:'温度',
        select:[
          {
            size:'热',
            price:'0'
          },
          {
            size:'冷',
            price:'0'
          }
        ]
      },
      {
        title:'糖度',
        select:[
          {
            size:'不另外加糖',
            price:'0'
          },
          {
            size:'半糖',
            price:'0'
          },
          {
            size:'标准糖',
            price:'0'
          }
        ]
      },
    ]
  },
  {
    title:'美式咖啡',
    price:'149',
    originalPrice:'229',
    sale:'400',
    gabalnara:false,
    url:'/image/index_img/merchandise/coffee007.jpg',
    information:[
      {
        title:'杯型',
        select:[
          {
            size:'大杯',
            price:'5'
          },
          {
            size:'中杯',
            price:'3'
          },
          {
            size:'小杯',
            price:'0'
          }
        ]
      },
      {
        title:'温度',
        select:[
          {
            size:'热',
            price:'0'
          },
          {
            size:'冷',
            price:'0'
          }
        ]
      },
      {
        title:'糖度',
        select:[
          {
            size:'不另外加糖',
            price:'0'
          },
          {
            size:'半糖',
            price:'0'
          },
          {
            size:'标准糖',
            price:'0'
          }
        ]
      },
    ]
  },
  {
    title:'拿铁',
    price:'159',
    originalPrice:'276',
    sale:'28200',
    gabalnara:true,
    url:'/image/index_img/merchandise/coffee008.jpg',
    information:[
      {
        title:'杯型',
        select:[
          {
            size:'大杯',
            price:'5'
          },
          {
            size:'中杯',
            price:'3'
          },
          {
            size:'小杯',
            price:'0'
          }
        ]
      },
      {
        title:'温度',
        select:[
          {
            size:'热',
            price:'0'
          },
          {
            size:'冷',
            price:'0'
          }
        ]
      },
      {
        title:'糖度',
        select:[
          {
            size:'不另外加糖',
            price:'0'
          },
          {
            size:'半糖',
            price:'0'
          },
          {
            size:'标准糖',
            price:'0'
          }
        ]
      },
    ]
  },
  {
    title:'摩卡',
    price:'88',
    originalPrice:'188',
    sale:'28200',
    gabalnara:true,
    url:'/image/index_img/merchandise/coffee009.jpg',
    information:[
      {
        title:'杯型',
        select:[
          {
            size:'大杯',
            price:'5'
          },
          {
            size:'中杯',
            price:'3'
          },
          {
            size:'小杯',
            price:'0'
          }
        ]
      },
      {
        title:'温度',
        select:[
          {
            size:'热',
            price:'0'
          },
          {
            size:'冷',
            price:'0'
          }
        ]
      },
      {
        title:'糖度',
        select:[
          {
            size:'不另外加糖',
            price:'0'
          },
          {
            size:'半糖',
            price:'0'
          },
          {
            size:'标准糖',
            price:'0'
          }
        ]
      },
    ]
  },
  {
    title:'卡布奇诺',
    price:'99',
    originalPrice:'129',
    sale:'100',
    gabalnara:true,
    url:'/image/index_img/merchandise/coffee010.jpg',
    information:[
      {
        title:'杯型',
        select:[
          {
            size:'大杯',
            price:'5'
          },
          {
            size:'中杯',
            price:'3'
          },
          {
            size:'小杯',
            price:'0'
          }
        ]
      },
      {
        title:'温度',
        select:[
          {
            size:'热',
            price:'0'
          },
          {
            size:'冷',
            price:'0'
          }
        ]
      },
      {
        title:'糖度',
        select:[
          {
            size:'不另外加糖',
            price:'0'
          },
          {
            size:'半糖',
            price:'0'
          },
          {
            size:'标准糖',
            price:'0'
          }
        ]
      },
    ]
  },
  {
    title:'焦糖玛奇朵',
    price:'178',
    originalPrice:'258',
    sale:'7000',
    gabalnara:false,
    url:'/image/index_img/merchandise/coffee011.jpg',
    information:[
      {
        title:'杯型',
        select:[
          {
            size:'大杯',
            price:'5'
          },
          {
            size:'中杯',
            price:'3'
          },
          {
            size:'小杯',
            price:'0'
          }
        ]
      },
      {
        title:'温度',
        select:[
          {
            size:'热',
            price:'0'
          },
          {
            size:'冷',
            price:'0'
          }
        ]
      },
      {
        title:'糖度',
        select:[
          {
            size:'不另外加糖',
            price:'0'
          },
          {
            size:'半糖',
            price:'0'
          },
          {
            size:'标准糖',
            price:'0'
          }
        ]
      },
    ]
  },
  {
    title:'浓缩咖啡',
    price:'139',
    originalPrice:'179',
    sale:'35',
    gabalnara:true,
    url:'/image/index_img/merchandise/coffee012.jpg',
    information:[
      {
        title:'杯型',
        select:[
          {
            size:'大杯',
            price:'5'
          },
          {
            size:'中杯',
            price:'3'
          },
          {
            size:'小杯',
            price:'0'
          }
        ]
      },
      {
        title:'温度',
        select:[
          {
            size:'热',
            price:'0'
          },
          {
            size:'冷',
            price:'0'
          }
        ]
      },
      {
        title:'糖度',
        select:[
          {
            size:'不另外加糖',
            price:'0'
          },
          {
            size:'半糖',
            price:'0'
          },
          {
            size:'标准糖',
            price:'0'
          }
        ]
      },
    ]
  },
  {
    title:'馥芮白',
    price:'239',
    originalPrice:'339',
    sale:'800',
    gabalnara:true,
    url:'/image/index_img/merchandise/coffee013.jpg',
    information:[
      {
        title:'杯型',
        select:[
          {
            size:'大杯',
            price:'5'
          },
          {
            size:'中杯',
            price:'3'
          },
          {
            size:'小杯',
            price:'0'
          }
        ]
      },
      {
        title:'温度',
        select:[
          {
            size:'热',
            price:'0'
          },
          {
            size:'冷',
            price:'0'
          }
        ]
      },
      {
        title:'糖度',
        select:[
          {
            size:'不另外加糖',
            price:'0'
          },
          {
            size:'半糖',
            price:'0'
          },
          {
            size:'标准糖',
            price:'0'
          }
        ]
      },
    ]
  },
  {
    title:'榛果风味拿铁',
    price:'178',
    originalPrice:'258',
    sale:'7000',
    gabalnara:false,
    url:'/image/index_img/merchandise/coffee014.jpg',
    information:[
      {
        title:'杯型',
        select:[
          {
            size:'大杯',
            price:'5'
          },
          {
            size:'中杯',
            price:'3'
          },
          {
            size:'小杯',
            price:'0'
          }
        ]
      },
      {
        title:'温度',
        select:[
          {
            size:'热',
            price:'0'
          },
          {
            size:'冷',
            price:'0'
          }
        ]
      },
      {
        title:'糖度',
        select:[
          {
            size:'不另外加糖',
            price:'0'
          },
          {
            size:'半糖',
            price:'0'
          },
          {
            size:'标准糖',
            price:'0'
          }
        ]
      },
    ]
  },
  {
    title:'香草风味拿铁',
    price:'178',
    originalPrice:'258',
    sale:'7000',
    gabalnara:true,
    url:'/image/index_img/merchandise/coffee015.jpg',
    information:[
      {
        title:'杯型',
        select:[
          {
            size:'大杯',
            price:'5'
          },
          {
            size:'中杯',
            price:'3'
          },
          {
            size:'小杯',
            price:'0'
          }
        ]
      },
      {
        title:'温度',
        select:[
          {
            size:'热',
            price:'0'
          },
          {
            size:'冷',
            price:'0'
          }
        ]
      },
      {
        title:'糖度',
        select:[
          {
            size:'不另外加糖',
            price:'0'
          },
          {
            size:'半糖',
            price:'0'
          },
          {
            size:'标准糖',
            price:'0'
          }
        ]
      },
    ]
  },
  {
    title:'焦糖浓缩咖啡',
    price:'99',
    originalPrice:'149',
    sale:'500',
    gabalnara:false,
    url:'/image/index_img/merchandise/coffee016.jpg',
    information:[
      {
        title:'杯型',
        select:[
          {
            size:'大杯',
            price:'5'
          },
          {
            size:'中杯',
            price:'3'
          },
          {
            size:'小杯',
            price:'0'
          }
        ]
      },
      {
        title:'温度',
        select:[
          {
            size:'热',
            price:'0'
          },
          {
            size:'冷',
            price:'0'
          }
        ]
      },
      {
        title:'糖度',
        select:[
          {
            size:'不另外加糖',
            price:'0'
          },
          {
            size:'半糖',
            price:'0'
          },
          {
            size:'标准糖',
            price:'0'
          }
        ]
      },
    ]
  },
  {
    title:'抹茶咖啡',
    price:'168',
    originalPrice:'258',
    sale:'41900',
    gabalnara:true,
    url:'/image/index_img/merchandise/coffee017.jpg',
    information:[
      {
        title:'杯型',
        select:[
          {
            size:'大杯',
            price:'5'
          },
          {
            size:'中杯',
            price:'3'
          },
          {
            size:'小杯',
            price:'0'
          }
        ]
      },
      {
        title:'温度',
        select:[
          {
            size:'热',
            price:'0'
          },
          {
            size:'冷',
            price:'0'
          }
        ]
      },
      {
        title:'糖度',
        select:[
          {
            size:'不另外加糖',
            price:'0'
          },
          {
            size:'半糖',
            price:'0'
          },
          {
            size:'标准糖',
            price:'0'
          }
        ]
      },
    ]
  },
  {
    title:'芒果西番莲果茶',
    price:'148',
    originalPrice:'258',
    sale:'200',
    gabalnara:false,
    url:'/image/index_img/merchandise/coffee018.jpg',
    information:[
      {
        title:'杯型',
        select:[
          {
            size:'大杯',
            price:'5'
          },
          {
            size:'中杯',
            price:'3'
          },
          {
            size:'小杯',
            price:'0'
          }
        ]
      },
      {
        title:'温度',
        select:[
          {
            size:'热',
            price:'0'
          },
          {
            size:'冷',
            price:'0'
          }
        ]
      },
      {
        title:'糖度',
        select:[
          {
            size:'不另外加糖',
            price:'0'
          },
          {
            size:'半糖',
            price:'0'
          },
          {
            size:'标准糖',
            price:'0'
          }
        ]
      },
    ]
  },
  {
    title:'芒果西番莲果茶',
    price:'148',
    originalPrice:'258',
    sale:'200',
    gabalnara:true,
    url:'/image/index_img/merchandise/coffee019.jpg',
    information:[
      {
        title:'杯型',
        select:[
          {
            size:'大杯',
            price:'5'
          },
          {
            size:'中杯',
            price:'3'
          },
          {
            size:'小杯',
            price:'0'
          }
        ]
      },
      {
        title:'温度',
        select:[
          {
            size:'热',
            price:'0'
          },
          {
            size:'冷',
            price:'0'
          }
        ]
      },
      {
        title:'糖度',
        select:[
          {
            size:'不另外加糖',
            price:'0'
          },
          {
            size:'半糖',
            price:'0'
          },
          {
            size:'标准糖',
            price:'0'
          }
        ]
      },
    ]
  },
  {
    title:'摩卡',
    price:'128',
    originalPrice:'258',
    sale:'3547',
    gabalnara:false,
    url:'/image/index_img/merchandise/coffee020.jpg',
    information:[
      {
        title:'杯型',
        select:[
          {
            size:'大杯',
            price:'5'
          },
          {
            size:'中杯',
            price:'3'
          },
          {
            size:'小杯',
            price:'0'
          }
        ]
      },
      {
        title:'温度',
        select:[
          {
            size:'热',
            price:'0'
          },
          {
            size:'冷',
            price:'0'
          }
        ]
      },
      {
        title:'糖度',
        select:[
          {
            size:'不另外加糖',
            price:'0'
          },
          {
            size:'半糖',
            price:'0'
          },
          {
            size:'标准糖',
            price:'0'
          }
        ]
      },
    ]
  },
  {
    title:'摩卡可可碎片',
    price:'241',
    originalPrice:'356',
    sale:'35407',
    gabalnara:true,
    url:'/image/index_img/merchandise/coffee021.jpg',
    information:[
      {
        title:'杯型',
        select:[
          {
            size:'大杯',
            price:'5'
          },
          {
            size:'中杯',
            price:'3'
          },
          {
            size:'小杯',
            price:'0'
          }
        ]
      },
      {
        title:'温度',
        select:[
          {
            size:'热',
            price:'0'
          },
          {
            size:'冷',
            price:'0'
          }
        ]
      },
      {
        title:'糖度',
        select:[
          {
            size:'不另外加糖',
            price:'0'
          },
          {
            size:'半糖',
            price:'0'
          },
          {
            size:'标准糖',
            price:'0'
          }
        ]
      },
    ]
  },
  {
    title:'香草风味',
    price:'141',
    originalPrice:'356',
    sale:'35807',
    gabalnara:false,
    url:'/image/index_img/merchandise/coffee022.jpg',
    information:[
      {
        title:'杯型',
        select:[
          {
            size:'大杯',
            price:'5'
          },
          {
            size:'中杯',
            price:'3'
          },
          {
            size:'小杯',
            price:'0'
          }
        ]
      },
      {
        title:'温度',
        select:[
          {
            size:'热',
            price:'0'
          },
          {
            size:'冷',
            price:'0'
          }
        ]
      },
      {
        title:'糖度',
        select:[
          {
            size:'不另外加糖',
            price:'0'
          },
          {
            size:'半糖',
            price:'0'
          },
          {
            size:'标准糖',
            price:'0'
          }
        ]
      },
    ]
  },
]
module.exports = { bananaList, activityList, commodityList }